theme: jekyll-theme-cayman
# Site settings
title: Nie's blog
SEOTitle: 聂君同学的博客

email: 15730475447@163.com
description: "No pains, no gains."
keyword: "聂君同学的博客, python,mysql,mangodb"
url: "https://nj-lixin.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/dabi-nj/dabi-nj.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "但行好事，莫问前程。"
sidebar-avatar:  /img/will-wang.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`
